### ISSUE TITLE
Generated go client doesn't support returning different bodies for different response statuses

### ISSUE THREAD

**Issue by serboctor** [Jumpscale/go-raml#330] opened 2017-11-02 11:07 UTC
If you generate a go client for the following raml:
```
          /{jobid}:
            uriParameters:
              jobid:
                type: string
            get:
              displayName: getJob
              description: Get a jobid
              responses:
                200:
                  body:
                    application/json:
                      type: Job
                404:
                  body:
                    application/json:
                      type: Error

```
The generated function will be as follows:
```
// Get a jobid
func (s *AysService) GetJob(jobid, repository string, headers, queryParams map[string]interface{}) (Job, *http.Response, error) {
	var u Job

	resp, err := s.client.doReqNoBody("GET", s.client.BaseURI+"/ays/repository/"+repository+"/job/"+jobid, headers, queryParams)
	if err != nil {
		return u, nil, err
	}
	defer resp.Body.Close()

	return u, resp, json.NewDecoder(resp.Body).Decode(&u)
}
```
This is ok for when the response status is 200, however for the 400 cases for example, the returned body is different so the decoding will fail and we will lose the info in the body. 
As a result we end up hacking the generated the client which we should ideally never touch. 
We need the generated client to support decoding and returned different body types for the different resposne statuses defined in the raml file.

**Comment by zaibon** [comment] 2017-11-02 11:19
Also, I think that the response object that is returned should have a body that can be use by the client.
Currently, once the `resp.Body` is read once, there is no way for the client to use it anymore.
We could read the body in a buffer, use the buffer data to unmahsarall the body into object and then set the buffer content back on the response object so the client can read from it again.

**Comment by iwanbk** [comment] 2017-11-02 13:23
> As a result we end up hacking the generated the client 

How is your modified client?
It might end up become our solution.

On the other hand, i proposes that the generated client only decodes the data when response code is 2xx.
I'm sure that 3xx will never need to be decoded and 4xx is always error.

**Comment by iwanbk** [comment] 2017-11-06 06:18
> We need the generated client to support decoding and returned different body types for the different resposne statuses defined in the raml file.

One obvious issue for this is that an API might have many different response codes.
If we do this way, we might have too many return values for the respective funcs.
It is possible from generator point of view, but the generated code might be too ugly.

**Comment by serboctor** [comment] 2017-11-08 15:19
> How is your modified client?
We don't fix it in the client itself, we just skip the decoding step, and return the reponse. And the function that uses the client, unmarshals the response body into the correct object depending on the response status then closes the body. Very icky.
> On the other hand, i proposes that the generated client only decodes the data when response code is >2xx.
>I'm sure that 3xx will never need to be decoded and 4xx is always error.
Well, the reason we did the icky modification is because wanted to propagate the errors from ays to rchestrator which is impossible with curent go-raml generation because unmarshaling the response will fail.

**Comment by iwanbk** [comment] 2017-11-09 02:48
> On the other hand, i proposes that the generated client only decodes the data when response code is 2xx.
> I'm sure that 3xx will never need to be decoded and 4xx is always error.

So, if the response code is other than 2xx, the user need to decode it by himself.

> 
Well, the reason we did the icky modification is because wanted to propagate the errors from ays to rchestrator which is impossible with curent go-raml generation because unmarshaling the response will fail.

So, how about my proposal?

**Comment by serboctor** [comment] 2017-11-09 07:36
So you propose that you only decode the data if the response code is 2xx, but in addition, you'll return the response body and the user can decode it himself if the response status is something other than 2xx?
That sounds reasonable to me.

**Comment by iwanbk** [comment] 2017-11-09 07:37
> So you propose that you only decode the data if the response code is 2xx, but in addition, you'll return the response body and the user can decode it himself if the response status is something other than 2xx?
> That sounds reasonable to me.

Yes

**Comment by zaibon** [comment] 2017-11-09 07:39
I don't see why if the user define a body for status code within  400 range we won't decode it ourselves.
Online decoding for success make the behavior non consistent. I think everything define in the raml spec should be generated. And we still return the response with a valid body tu the user so it can always do whatever if he needs to

**Comment by serboctor** [comment] 2017-11-09 07:44
> One obvious issue for this is that an API might have many different response codes.
If we do this way, we might have too many return values for the respective funcs.
It is possible from generator point of view, but the generated code might be too ugly.

Maybe instead the functions can return an interface and the user would be responsible for casting it. I know it is an overhead and will make things repetitive, but I also agree that the generated code might end up being too ugly..

**Comment by zaibon** [comment] 2017-11-09 07:46
Empty interface are bad and break the type safety.
I don't really see why it would be too ugly. A switch on the status  code that calls the proper method to decode the response. Doesn't look too bad IMO

**Comment by iwanbk** [comment] 2017-11-09 07:46
> I don't see why if the user define a body for status code within 400 range we won't decode it ourselves.
> only decoding for success make the behavior non consistent. I think everything define in the raml spec should be generated. And we still return the response with a valid body tu the user so it can always do whatever if he needs to

I don't propose to handle each status code because:
- there might be many status codes, then the API will return too many values, which is ugly.
- some error condition might not be declared properly in .raml or returning non json

Some example of the last point is described at https://github.com/Jumpscale/go-raml/issues/339#issue-272221944

> If the 404 or 409 status code get returned (or 401/403 by the security middleware, not included in the raml fragment), the client seemingly returns nothing. If the server also returns a status text (either the string representation of the code or something custom, e.g.: 404 -> Not found), the client returns an error because this is not valid json. This is often the case when the server returns a 4xx (or 5xx) status code throught go's http.Error function, e.g.: http.Error(w, http.StatusText(http.StatusNotFound), http.StatusNotFound). I feel like the generated client should ignore the body in this case since no return body is declared in the raml file

It is true that server should document all status code properly, but client should should handle faulty server as well. And sometimes the server lives behind other entity (load balancer etc) which might return different code

**Comment by iwanbk** [comment] 2017-11-09 07:49
> I don't really see why it would be too ugly. A switch on the status code that calls the proper method to decode the response. Doesn't look too bad IMO

If there are 4 status code
it might be something like
```
func (s *AysService) GetJob(jobid, repository string, headers, queryParams map[string]interface{}) (Status1, status2, status3, status4, *http.Response, error) {
```

But yeah, different status code might have same error type

**Comment by zaibon** [comment] 2017-11-09 07:59
Hum yeah didn't though about the return values, this is definitely not ok.
Any idea how go-swagger handle this ?

**Comment by iwanbk** [comment] 2017-11-09 09:03
> Any idea how go-swagger handle this ?

Did a quick experiment based on this tutorial https://github.com/go-swagger/go-swagger/blob/master/docs/tutorial/todo-list.md

modified some endpoint to have many status code
```yaml
post:
      tags:
        - todos
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/item"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/item"
        202:
          description: Created
          schema:
            $ref: "#/definitions/item"
        401:
          description: Created
          schema:
            $ref: "#/definitions/error"
        404:
          description: Created
          schema:
            $ref: "#/definitions/error"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
```

 the generated code
```
func (a *Client) AddOne(params *AddOneParams) (*AddOneCreated, *AddOneAccepted, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddOneParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "addOne",
		Method:             "POST",
		PathPattern:        "/",
		ProducesMediaTypes: []string{"application/io.goswagger.examples.todo-list.v1+json"},
		ConsumesMediaTypes: []string{"application/io.goswagger.examples.todo-list.v1+json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &AddOneReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *AddOneCreated:
		return value, nil, nil
	case *AddOneAccepted:
		return nil, value, nil
	}
	return nil, nil, nil

}
```
the reader func
```
func (o *AddOneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewAddOneCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 202:
		result := NewAddOneAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewAddOneUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewAddOneNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewAddOneDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}
```

**Comment by iwanbk** [comment] 2017-11-09 09:16
It seems to try to decode all 2xx codes and make it return value
while for other status code, i'm still not sure, one thing for sure is that it become `error`

**Comment by iwanbk** [comment] 2017-11-09 09:56
in the meanwhile, i might need to implement my proposal because:
- current implementation is really buggy, user won't be able to read body when the server return error
- doesn't change the API
- quick to implement

**Comment by zaibon** [comment] 2017-11-09 09:58
Ok let fix thing in the meanwhile then. so we can unblock people and we'll improve in other PR

**Comment by LeeSmet** [comment] 2017-11-09 10:13
Just adding my 2 cents: since almost all endpoints return a single 2xx (with body) on success, or a possible 4xx (with optional error code), isn't there a possibility to do something where the return is 1. a decoded body and 2) a (custom) error type? Based on the return code the error can be populated. Callers then inspect if the error is nil, and if so they know the body is correctly decoded. If the error is not nil, there could be an `err.Type` that can be switched over with all the declared status codes, adding a 5xx status code that might not be declared (might be caused by proxy or load balancer as well), or an encapsulated runtime error thrown by the runtime (maybe decoding the body failed because the raml and actual api are out of sync...).

**Comment by iwanbk** [comment] 2017-11-10 03:01
> Ok let fix thing in the meanwhile then. so we can unblock people and we'll improve in other PR

I also not sure now with my proposal to only decode if status code is 2xx because in case of error the resp.Body won't be closed by generated code. And user might not close it as well.

**Comment by iwanbk** [comment] 2017-11-10 03:08
> Just adding my 2 cents: since almost all endpoints return a single 2xx (with body) on success, or a possible 4xx (with optional error code), isn't there a possibility to do something where the return is 1. a decoded body and 2) a (custom) error type? Based on the return code the error can be populated. Callers then inspect if the error is nil, and if so they know the body is correctly decoded. If the error is not nil, there could be an err.Type that can be switched over with all the declared status codes, adding a 5xx status code that might not be declared (might be caused by proxy or load balancer as well), or an encapsulated runtime error thrown by the runtime (maybe decoding the body failed because the raml and actual api are out of sync...).

I think it is the best idea so far, and i would like to implement it soon, with some addition:
- still returning response object
- the custom error is as follow

```go
type CustomError struct {
    Code int // http status code
    RawMessage string // Raw error response body
   
    // Message interface{} // parsed error response body : not sure about it
}

// returns RawMessage
func (ce CustomError) Error() 
```

**Comment by iwanbk** [comment] 2017-11-10 08:29
Some example of the generated files can be found on https://gist.github.com/iwanbk/168a360f8bfd7cb1eb14871e3a6e2ee0

Let me know your thought guys!

**Closed** 2017-11-14 04:35 UTC
Labels: state_inprogress, type_bug
