### ISSUE TITLE
Inline object definition are not properly generated

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/go-raml#226] opened 2017-03-03 12:46 UTC
raml source 
```raml
  Action:
    properties:
      name: string
      code: string
      state:
        enum: [ new, changed, ok, scheduled, disabled, error,running ]
      recurring:
        type: object
        properties:
          period:
            type: integer
            description: recurring period in second
          last_run:
            type: integer
            description: timestamp of last execution
```

golang client code generated:
```golang
type Action struct {
	Code      string          `json:"code" validate:"nonzero"`
	Name      string          `json:"name" validate:"nonzero"`
	Recurring object          `json:"recurring" validate:"nonzero"`
	State     EnumActionState `json:"state" validate:"nonzero"`
}
```

expected 
```golang
type Action struct {
	Code      string `json:"code" validate:"nonzero"`
	Name      string `json:"name" validate:"nonzero"`
	Recurring struct {
		Period  int64 `json:"period" validate:"nonzero"`
		LastRun int64 `json:"last_run" validate:"nonzero"`
	} `json:"recurring" validate:"nonzero"`
	State EnumActionState `json:"state" validate:"nonzero"`
}
```

possible duplicate of : https://github.com/Jumpscale/go-raml/issues/96

**Comment by iwanbk** [comment] 2017-03-08 13:16
duplicate of #96

**Closed by iwanbk** 2017-03-08 13:16 UTC
Labels: type_bug
